// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const ExportManager: typeof import('/home/runner/work/ai-answer-exporter/ai-answer-exporter/src/utils/exportManager')['ExportManager']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const OptionsApp: typeof import('/home/runner/work/ai-answer-exporter/ai-answer-exporter/src/components/OptionsApp')['default']
  const PopupApp: typeof import('/home/runner/work/ai-answer-exporter/ai-answer-exporter/src/components/PopupApp')['default']
  const SettingsManager: typeof import('/home/runner/work/ai-answer-exporter/ai-answer-exporter/src/utils/settings')['SettingsManager']
  const WebsiteDetector: typeof import('/home/runner/work/ai-answer-exporter/ai-answer-exporter/src/utils/websiteDetector')['WebsiteDetector']
  const browser: typeof import('wxt/browser')['browser']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const storage: typeof import('wxt/storage')['storage']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ExportManager } from '/home/runner/work/ai-answer-exporter/ai-answer-exporter/src/utils/exportManager'
  import('/home/runner/work/ai-answer-exporter/ai-answer-exporter/src/utils/exportManager')
  // @ts-ignore
  export type { SettingsManager } from '/home/runner/work/ai-answer-exporter/ai-answer-exporter/src/utils/settings'
  import('/home/runner/work/ai-answer-exporter/ai-answer-exporter/src/utils/settings')
  // @ts-ignore
  export type { WebsiteDetector } from '/home/runner/work/ai-answer-exporter/ai-answer-exporter/src/utils/websiteDetector'
  import('/home/runner/work/ai-answer-exporter/ai-answer-exporter/src/utils/websiteDetector')
}
